### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Sugar1y** [svyas23/GAMa#1]
Which video image set should I choose to download?
![image](https://user-images.githubusercontent.com/74653684/180347926-e6c2ab32-6472-473f-bf9e-2549a557e173.png)
And in your paper, you said that only part of the data set was used, so how did you choose?

**Comment by svyas23** [comment]
Please download videos and info files. We have only used the training and
validation set of these videos.
If you have downloaded aerial images, in that folder we have a few lists
(of videos selected for training and validation) and a readme file to help
you out.

-Shruti
