### ISSUE TITLE
some questions about the package util

### ISSUE THREAD

**Issue by miganchuanbo** [svyas23/GAMa#2]
i am using python3.6.9 , but i could not import util.where can i find it?

**Comment by svyas23** [comment]
Sorry about that. The util file is now added to the repository.
Thank you for highlighting this issue.


[image: width=]
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by miganchuanbo** [comment]
Thanks for that. But there is still some issue when I try to import the dataset.pyc file. Would you mind add the source file to the repo?

**Comment by svyas23** [comment]
I checked the repo. Instead of dataset.py pyc file got uploaded. I have
uploaded the correct file.

**Comment by miganchuanbo** [comment]
Thanks

**Comment by svyas23** [comment]
You do not need to download any.pyc files. They are not required.
