### ISSUE TITLE
questions about the dataset

### ISSUE THREAD

**Issue by XianghuiZe** [svyas23/GAMa#4]
Hello, I'm not very clear about some parts of this dataset. Can you help me?
In this project, we need to run extract_ frames. py to extract frames from video of bdd100k dataset. I can't judge whether I am right or wrong in this step. 
Firstly, The problem is that the frame I extracted is rotated 180 ° clockwise. Then, the number of frames extracted here is not exactly the same as that given in file train_day.list. For example, about video 07f1933b-8c2284ed.mov, I extracted 1205 pictures, but it is indicated in the train_day.list that the video has 1202 frames in total.
Did my operation cause an error? Can you give an example of this process? We look forward to your reply. Thank you very much.

**Comment by XianghuiZe** [comment]
And I want to ask, from Table 3 in the paper, [top-1, top-5, top-10, top-1%] = [15.2, 27.2, 33.8, 91.9] is the result of the Step-1 of the hierarchical approach?

**Comment by svyas23** [comment]
Hello zexianghui

Yes, the frames were extracted using extract_ frames. py however I am not
sure why the frames would rotate. There were some differences in the pixel
sizes/orientation of some videos which caused the issue. If you are seeing
the rotation with only some of the videos that may be the issue. It is
possible that an older file got shared. If it is fixed at your end please
let me know what was the problem.
Some of the frames (in 2-3 videos) got corrupt during my extraction and I
probably deleted/removed them. I would suggest to update/create the number
of frames using train_day.list as a list of video folders to iterate over.

**Comment by svyas23** [comment]
Yes, this is correct.

**Comment by XianghuiZe** [comment]
Thanks for your reply.
I run extract_ frames.py. All images I got are inverted. For example, about 0024b742-83709bd4.mov in the training set. The image I got is as follows. Is this the frame picture used in your experiment?
![image](https://user-images.githubusercontent.com/57891691/205420263-ea6864b0-d266-40af-9c1e-d62db3906887.png)
Thanks again for your reply.

**Comment by svyas23** [comment]
My frames were all straight without rotation. Maybe there is some error at
your end. See, if some transformation got uncommented.

**Comment by XianghuiZe** [comment]
This is the result of running extract_ frames. py directly. Would you please check the code?
Can you upload a result of extract_ frames. py for a video?Thanks very much.

**Comment by FLAGRARdwb** [comment]
> This is the result of running extract_ frames. py directly. Would you please check the code? Can you upload a result of extract_ frames. py for a video?Thanks very much.

Same problem! I've spent a lot of time understanding the code. Were you able to fix it? @svyas23 Thank you for your time.

**Comment by svyas23** [comment]
> And I want to ask, from Table 3 in the paper, [top-1, top-5, top-10, top-1%] = [15.2, 27.2, 33.8, 91.9] is the result of the Step-1 of the hierarchical approach?

Yes that's true

**Comment by Mabel0403** [comment]
I have a similar concern regarding the dataset processing code "extract_ frames. py". The original code I pulled from your repository might have some bugs and cannot be run directly. After the modification by myself, the same situation as others occurred: the extracted image was incorrect. Could you please take a look and help resolve them? Thank you!
