### ISSUE TITLE
Test set

### ISSUE THREAD

**Issue by nate-daba** [svyas23/GAMa#5]
In table 1 of the paper, it shows that the dataset contains 6506 test videos. However, I can't find the list of video names in the list folder for the test set. 

For example, for training, I was able to extract the frames from the videos using the list of videos names from the train.list file. However, there is no val.list or test.list file that contains a list of selected test video names. Can you please help me resolve this issue or am I missing something here?

Thank you.

**Comment by svyas23** [comment]
You probably figured it out. It is in the same folder, list. Look into
val_gps_day.list . Table or data format may be different.
Please let me know if there is another issue.

Thanks

**Comment by svyas23** [comment]
Sorry, I meant val_gps.list
