### ISSUE TITLE
train_day.list contains night videos

### ISSUE THREAD

**Issue by nate-daba** [svyas23/GAMa#6]
Hi,

I tried to extract the frames from day videos using the extract_frames.py and the train_day.list you provided. However, some of the extracted frames are in fact from videos captured during night time. Can you please confirm if this is the case on your side as well? And if yes, shouldn't the train_day.list contain only the day time videos as the name implies?

Thank you.

**Comment by svyas23** [comment]
The segregation of videos into day and night was based on a time cutoff. Sunset and sunrise time varies with location and month. That might have caused some less light videos to creep into the day list. Please let us know if you see many such videos.

**Comment by nate-daba** [comment]
Below are some of the video folder ids and sample frames from the folder that contain night time data.

Video folder: **000f157f-30b30f5e**
Frame file name: 0754.png
![0754](https://github.com/svyas23/GAMa/assets/121645562/bb7bd18d-5dbf-4c1a-b490-544bdd37dc53)

Video folder: **000f157f-37797ff9**
Frame file name: 0426.png
![0426](https://github.com/svyas23/GAMa/assets/121645562/921c45e8-d759-4c79-8385-77333c145224)

Video folder: 00d8d95a-47d98291
Frame file name: 1183.png
![1183](https://github.com/svyas23/GAMa/assets/121645562/2232ffdb-6d8a-4b0e-96ee-5913c86d86fd)

These are just few that I could find. There could be more.
